# Documentation - Using Libraries: Scipy
This educational notebook illustrates the use of the `scipy` library, a powerful library for scientific computing in Python.

It covers:
- Linear Algebra:
  - Determinant calculation
  - PLU Decomposition
  - Eigenvalue and Eigenvector
  - Solving Linear Equations
- Sparse Matrix Operations:
  - Creation and manipulation of sparse matrices
  - CSR Format
  - Solving Sparse Linear Equations

In [1]:
# %pip install numpy # uncomment this line to install
# %pip install scipy # uncomment this line to install

In [2]:
import numpy as np
from scipy import linalg, sparse # linear algebra and sparse
from scipy.sparse import linalg as splinalg # sparse's linear algebra

## 1. Determinant Calculation
A determinant is a scalar value that can be computed from the elements of a square matrix and encodes certain properties of the linear transformation described by the matrix. It is useful in various mathematical and scientific calculations, such as finding the inverse of a matrix, calculating volumes, and solving systems of linear equations.

We can calculate the determinant of a square matrix using the `linalg.det()` function.

In [3]:
A = np.array([[1, 2], [4, 5]])
detA = linalg.det(A)
print(A)
print(f"\nDeterminant = {detA:.2f}")

[[1 2]
 [4 5]]

Determinant = -3.00


## 2. PLU Decomposition
PLU decomposition is a matrix factorization technique that decomposes a square matrix into three matrices: 
- P is a permutation matrix (single one on each row & column)
- L is a lower triangular matrix with unit diagonal
- U is an upper triangular matrix with unit diagonal

This decomposition is useful in solving systems of linear equations, finding the inverse of a matrix, and computing determinants. The `linalg.lu()` function can be used to perform PLU decomposition.

In [4]:
P, L, U = linalg.lu(A)
print("\nP (Permutation matrix):")
print(P)
print("\nL (Lower triangular):")
print(L)
print("\nU (Upper triangular):")
print(U)


P (Permutation matrix):
[[0. 1.]
 [1. 0.]]

L (Lower triangular):
[[1.   0.  ]
 [0.25 1.  ]]

U (Upper triangular):
[[4.   5.  ]
 [0.   0.75]]


## 3. Eigenvalues and Eigenvectors
Eigenvalues and eigenvectors are important concepts in linear algebra. They are used in various applications, including differential equations, quantum mechanics, and data analysis.

When a linear transformation occurs, most vectors change both their direction and magnitude. However, some special vectors called eigenvectors change in magnitude only and remain in the same direction. The eigenvalue (λ) tells us exactly how much the eigenvector is stretched or compressed.

When a matrix A performs a linear transformation on an eigenvector v, the result is equivalent to scaling the vector by its corresponding eigenvalue λ. This is why we can write:

A * v = λ * v

where:
- A is square matrix
- v is eigenvector (column vector)
- λ is eigenvalue (diagonal matrix)

The eigenvalues and eigenvectors of a matrix can be found using the `linalg.eig()` function.

In [5]:
eigenvalues, eigenvectors = linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)

Eigenvalues: [-0.46410162+0.j  6.46410162+0.j]

Eigenvectors:
 [[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]


## 4. Solving Linear Equations
The `linalg.solve()` function can be used to solve a system of linear equations. It requires two inputs:
- a square matrix
- a column vector

and outputs a column vector which is the solution to the system of linear equations.

In [6]:
# Solving the system:
# 2x + 3y = 5
# x - y = 2
a = np.array([[2, 3], [1, -1]])
v = np.array([5, 2])
solution = linalg.solve(a, v)
print("\nSolution to Linear Equations:")
print(f"x = {solution[0]:.2f}")
print(f"y = {solution[1]:.2f}")


Solution to Linear Equations:
x = 2.20
y = 0.20


## 5. Sparse Matrix Operations
A sparse matrix is a matrix in which most of the elements are zero. Sparse matrices are commonly used in numerical computations where the majority of the data is zero, such as in linear algebra, graph theory, and machine learning.

The `sparse` library provides functions to create and manipulate sparse matrices. 
- `lil_matrix()` method -> create a sparse matrix
- `setdiag()` method -> sets the diagonal of the matrix
- `toarray()` method -> converts a sparse matrix to a dense array for display

In [7]:
# Create a sparse matrix
B = sparse.lil_matrix((10, 10)) # create a blank 10 x 10 matrix
B[:, :] = np.ones(10) # fill the matrix with ones
B.setdiag(np.ones(3) * 100) # set the diagonal of the matrix to 100
print(B.toarray())  # convert to dense array for display

[[100.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1. 100.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1. 100.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]]


## 6. CSR Format
The Compressed Sparse Row (CSR) format is a popular format for storing sparse matrices. It is efficient for performing operations on sparse matrices and is widely used in numerical libraries such as SciPy.

The `csr_matrix()` function can be used to convert a dense matrix to CSR format.

In [8]:
L = np.array([[1, 2, 4], [3, 7, 9], [2, 5, 6]])
print("Original Matrix:")
print(L)

# Convert to CSR format
L_sparse = sparse.csr_matrix(L)
print("\nCSR Format:")
print("Data:", L_sparse.data) # values in the matrix
print("Indices:", L_sparse.indices) # column indices of the non-zero elements

print("Indptr:", L_sparse.indptr) # row pointers to the start of each row
    # Row 0 starts at position 0 and contains elements from index 0 to 3
    # Row 1 starts at position 3 and contains elements from index 3 to 6
    # Row 2 starts at position 6 and contains elements from index 6 to 9
    # The final value (9) marks the end of the last row

Original Matrix:
[[1 2 4]
 [3 7 9]
 [2 5 6]]

CSR Format:
Data: [1 2 4 3 7 9 2 5 6]
Indices: [0 1 2 0 1 2 0 1 2]
Indptr: [0 3 6 9]


## 7. Solving Sparse Linear Equations
The `splinalg.spsolve()` function can be used to solve a system of linear equations with sparse matrices. The function requires two inputs:
- a sparse matrix
- a column vector

and outputs a column vector which is the solution to the system of linear equations.

In [9]:
splinalg.spsolve(L_sparse, np.array([1, 2, 3])) # solve the system of linear equations

array([-17.,   5.,   2.])